fix(auth): allow username set to "default"
Kong/resty-redis-cluster pull request #25
Opened 2023-10-27 03:25 UTC by outsinre

To be compatibile with Redis before `6.0`, supporting ACL with `default` username.

2023-10-30 07:24 UTC, tzssangglass approved these changes

2023-10-30 13:03 UTC, jschmid1 requested changes
So, redis versions < 6 had a default user called "default" which we didn't allow to be used from within Kong?

The "fix" is to lift this restriction? What prevents a user from using older redis versions that still have the "default" user?

2023-10-30 13:10 UTC, outsinre commented
> So, redis versions < 6 had a default user called "default" which we didn't allow to be used from within Kong?
> 
> The "fix" is to lift this restriction? What prevents a user from using older redis versions that still have the "default" user?

@jschmid1 ,

Redis < 6.0 does NOT has the `username` concept but only `password`.

From 6.0 onwards, both `username` and `password` are used. To be backward compatible with < 6.0, the `username` can be set to a fixed value `default`.

The library currently disallows configuring `username` as `default`. This PR relaxes the restriction.

2023-10-31 09:13 UTC, jschmid1 approved these changes

2023-10-31 09:16 UTC, jschmid1 commented
Looks like we don't have the tests running automatically. This would be a good next step @outsinre

2023-10-31 09:16 UTC, merged